options:
  logging: CLOUD_LOGGING_ONLY
steps:
# 1. Build the Docker Image 
- name: 'gcr.io/cloud-builders/docker'
  id: Build
  args: 
    - 'build' 
    - '-t' 
    - 'gcr.io/$PROJECT_ID/gvl2025-workshop:$SHORT_SHA' 
    # --- Inject all 7 Firebase values as build arguments using Substitutions ---
    # We use ${_VAR_NAME} which Cloud Build replaces with values from your Trigger settings
    - '--build-arg' 
    - 'NEXT_PUBLIC_FIREBASE_API_KEY=${_FIREBASE_API_KEY}'
    - '--build-arg'
    - 'NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN=${_FIREBASE_AUTH_DOMAIN}'
    - '--build-arg'
    - 'NEXT_PUBLIC_FIREBASE_PROJECT_ID=${_FIREBASE_PROJECT_ID}'
    - '--build-arg'
    - 'NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET=${_FIREBASE_STORAGE_BUCKET}'
    - '--build-arg'
    - 'NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID=${_FIREBASE_MESSAGING_SENDER_ID}'
    - '--build-arg'
    - 'NEXT_PUBLIC_FIREBASE_APP_ID=${_FIREBASE_APP_ID}'
    - '--build-arg'
    - 'NEXT_PUBLIC_FIREBASE_MEASUREMENT_ID=${_FIREBASE_MEASUREMENT_ID}'
    - '.' 

# 2. Push the Docker Image 
- name: 'gcr.io/cloud-builders/docker'
  id: Push
  args: ['push', 'gcr.io/$PROJECT_ID/gvl2025-workshop:$SHORT_SHA'] 

# 3. Deploy to Cloud Run
- name: 'gcr.io/cloud-builders/gcloud'
  id: Deploy
  args:
  - 'run'
  - 'deploy'
  - 'gvl-webapp'
  - '--image=gcr.io/$PROJECT_ID/gvl2025-workshop:$SHORT_SHA'
  - '--region=us-central1'
  - '--no-allow-unauthenticated'
  # Since you already set the env vars in the Cloud Run UI (your screenshot),
  # we do NOT need to set them again here. Cloud Run preserves existing variables
  # unless you overwrite them. This keeps your YAML cleaner.

# # Corrected cloudbuild.yaml
# options:
#   logging: CLOUD_LOGGING_ONLY
# steps:
# # 1. Build the Docker Image 
# - name: 'gcr.io/cloud-builders/docker'
#   id: Build
#   args: ['build', '-t', 'gcr.io/$PROJECT_ID/gvl2025-workshop:$SHORT_SHA','--build-arg','NEXT_PUBLIC_FIREBASE_API_KEY=$$FIREBASE_API_KEY_SECRET', '.'] 
#   secretEnv: ['FIREBASE_API_KEY_SECRET']
# secrets:
# - secret: projects/$PROJECT_ID/secrets/my-firebase-api-key-secret/versions/latest # <-- Replace 'my-firebase-api-key-secret' with your Secret ID
#   env: 'FIREBASE_API_KEY_SECRET'

# # 2. Push the Docker Image 
# - name: 'gcr.io/cloud-builders/docker'
#   id: Push
#   args: ['push', 'gcr.io/$PROJECT_ID/gvl2025-workshop:$SHORT_SHA'] 

# # 3. Deploy the new version to Cloud Run
# - name: 'gcr.io/cloud-builders/gcloud'
#   id: Deploy
#   args:
#   - 'run'
#   - 'deploy'
#   - 'gvl-webapp'
#   - '--image=gcr.io/$PROJECT_ID/gvl2025-workshop:$SHORT_SHA' # <-- This path is now consistent
#   - '--region=us-central1'
#   - '--no-allow-unauthenticated'